# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mdemiche <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/07 20:26:27 by mdemiche          #+#    #+#              #
#    Updated: 2018/11/08 22:21:04 by mdemiche         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all: ft_display_file

ft_display_file: 
	gcc -Wall -Werror -Wextra display_file.c -o ft_display_file

clean:
	/bin/rm -f *.o

fclean: clean
	/bin/rm -f ft_display_file

re: fclean all 
